<?php require('template/header.phtml') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" enctype="multipart/form-data" >
    <div class=form-group">
        <label for="id">Student ID</label>
        <input type="text" class="form-control" placeholder="Enter student ID" name="id" value="<?php if (isset($_POST['id'])) echo
        $_POST['id']; ?>" >

        <label for="first_name">First name</label>
        <input type="text" class="form-control" placeholder="Enter first name" name="first_name" value="<?php if (isset($_POST['first_nnme'])) echo
        $_POST['first_name']; ?>" >

        <label for="last_name">Last name</label>
        <input type="text" class="form-control" placeholder="Enter last name" name="last_name" value="<?php if (isset($_POST['last_name'])) echo
        $_POST['last_name']; ?>" >

        <label for="international">International</label><input type="text" class="form-control" placeholder="Enter yes/no" name="international" value="<?php if (isset($_POST['international'])) echo
        $_POST['international']; ?>" >

        <label for="courseID">Course ID</label>
        <input type="text" class="form-control" placeholder="Enter course ID" name="courseID" value="<?php if (isset($_POST['courseID'])) echo
        $_POST['courseID']; ?>" >

        <br>
        <div class="'radio">
            <label for="op"> Select an option</label>

            <div><input type="radio" name="op" value="cdbase"> Create entry (fill all fields)</div>
            <div><input type="radio" name="op" value="rdbase" checked> Retrieve  (enter: nothing for <strong>all</strong>>; <strong>Last name</strong> or <strong>CourseID</strong>) </div>
            <div><input type="radio" name="op" value="udbase" > Update (fill all fields) </div>
            <div><input type="radio" name="op" value="ddbase" > Delete Student ID </div>
            <br>
            <div><input type="radio" name="op" value="adbase"> Add/change photo (enter Student ID)  <input type="file" name="photo"> </div>
        </div>
        <br>
        <input type="submit" class="btn btn-default" value="Submit" name="submit">
        <input type="reset" class="btn btn-default" name="reset">
</form>
    
<?php
    if (isset($view->studentsDataSet)) {
        if (count($view->studentsDataSet)>0) {
            echo '<br><br>';
            echo '<table class="table table-hover"><thead><tr>';
            echo '<th>Student ID</th><th>First name</th><th>Last name</th><th>International</th><th>Photo</th><th>CourseID</th></tr>';
            echo '</thead><tbody>';
            foreach ($view->studentsDataSet as $studentData) {
      
                echo '<tr><td>' . $studentData->getStudentID(). '</td><td>' . $studentData->getFirstName() . '</td><td>' . $studentData->getLastName() . '</td><td>' . $studentData->getInternational() . '</td><td>' . '<img src="images/' . $studentData->getPhotoName() . '" alt="no picture" />' . '</td><td>' . $studentData->getCourseID() . '</td></td></tr>';
              }
        echo '</tbody></table>';
        } else {
            echo 'No data matched the query';
        }
            
    };
?>



<?php require('template/footer.phtml') ?>
